name: Release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'package.json'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.release.outputs.releaseID }}

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - uses: actions/setup-node@ee36e8b5c0fdd6014a0398aed18ce9876360bd63
      with:
        node-version: 20
    - name: Build and package
      run: |
        yarn
        yarn package
    - name: Commit changes
      uses: planetscale/ghcommit-action@5cd5ba8c2ef5c6e6d90f856d36e700fb79183e68
      with:
        commit_message: "Update dist/index.js"
        repo: ${{ github.repository }}
        branch: ${{ github.head_ref || github.ref_name }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Make release
      id: release
      uses: Kas-tle/base-release-action@95bf169cd0975b3fba91535309d416801aa97a38
      with:
        files: |
          dist/index.js
        appID: ${{ secrets.RELEASE_APP_ID }}
        appPrivateKey: ${{ secrets.RELEASE_APP_PK }}

  upload-logs:
    name: Upload Logs
    runs-on: ubuntu-latest
    needs: release

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Upload logs
      uses: ./
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        releaseID: ${{ needs.release.outputs.release_id }}